### ISSUE TITLE
Necessary file missing!

### ISSUE THREAD

**Issue by Qingqingniu** [ml-research/deictic-segment-anything#2]
Thank you for your great word, and recently I have been running Part 1: To solve DeiVG using DeiSAM: I encountered some file missing issues, the exact file path is as follows: 'data/visual_genome/by-id/2358761.json
Where do I need to download them，or can you just give them to me , or how to generate it ？
Thank you very much！

**Comment by hkrsnd** [comment]
Hi, thank you for your feedback! Could you provide the entire error message so that I can see where it's happening?

**Comment by Qingqingniu** [comment]
@hkrsnd The entire error message is like this:
Deictic representation:
    an object that is near a giraffe.
Traceback (most recent call last):
  File "src/solve_deivg.py", line 412, in <module>
    results = segment_by_deisam(
  File "src/solve_deivg.py", line 53, in segment_by_deisam
    graph = vg.load_scene_graph_by_id(image_id)
  File "/deictic-segment-anything/src/data_vg.py", line 218, in load_scene_graph_by_id
    scene_graph = vg.get_scene_graph(
  File "/anaconda3/envs/sam2/lib/python3.8/site-packages/visual_genome/local.py", line 75, in get_scene_graph
    data = json.load(open(image_data_dir + fname, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/visual_genome/by-id/2358761.json'

**Comment by hkrsnd** [comment]
Thank you for sharing this.  I will investigate why the folder is not there by default. Anyway I uploaded the corresponding folder as a zip file here so you can download: [https://hessenbox.tu-darmstadt.de/getlink/fi6SZCx2U9sY18o535fxUSEG/by-id.zip]( https://hessenbox.tu-darmstadt.de/getlink/fi6SZCx2U9sY18o535fxUSEG/by-id.zip)

I will update the README in a few days, including all necessary file links.

**Comment by Qingqingniu** [comment]
@hkrsnd will the links in the README include file 'synsets.json' as well ,the entire error message like this:
Deictic representation:
    an object that is near a giraffe.
Traceback (most recent call last):
  File "src/solve_deivg.py", line 412, in <module>
    results = segment_by_deisam(
  File "src/solve_deivg.py", line 53, in segment_by_deisam
    graph = vg.load_scene_graph_by_id(image_id)
  File "/deictic-segment-anything/src/data_vg.py", line 218, in load_scene_graph_by_id
    scene_graph = vg.get_scene_graph(
  File "/anaconda3/envs/sam2/lib/python3.8/site-packages/visual_genome/local.py", line 78, in get_scene_graph
    scene_graph = init_synsets(scene_graph, synset_file)
  File "/anaconda3/envs/sam2/lib/python3.8/site-packages/visual_genome/local.py", line 200, in init_synsets
    syn_data = json.load(open(synset_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/visual_genome/synsets.json'
